joint_limits:
  joint1:
    # has_acceleration_limits: false
    # has_effort_limits: true
    # has_position_limits: true
    # has_velocity_limits: true
    min_position: -3.107
    max_position: 3.107
    max_velocity: 1.0
    max_effort: 100.0
  joint2:
    min_position: -2.269
    max_position: 2.269
    max_velocity: 1.0
    max_effort: 100.0
  joint3:
    min_position: -2.356
    max_position: 2.356
    max_velocity: 1.0
    max_effort: 100.0
  joint4:
    min_position: -3.107
    max_position: 3.107
    max_velocity: 1.0
    max_effort: 100.0
  joint5:
    min_position: -2.234
    max_position: 2.234
    max_velocity: 1.0
    max_effort: 100.0
  joint6:
    min_position: -6.283
    max_position: 6.283
    max_velocity: 1.0
    max_effort: 100.0
