joint_limits:
  joint1:
    # has_acceleration_limits: false
    # has_effort_limits: true
    # has_position_limits: true
    # has_velocity_limits: true
    min_position: !degrees -178.0
    max_position: !degrees 178.0
    max_velocity: !degrees 180.0
    max_effort: 60.0
  joint2:
    min_position: !degrees -130.0
    max_position: !degrees 130.0
    max_velocity: !degrees 180.0
    max_effort: 60.0
  joint3:
    min_position: !degrees -178.0
    max_position: !degrees 178.0
    max_velocity: !degrees 225.0
    max_effort: 30.0
  joint4:
    min_position: !degrees -135.0
    max_position: !degrees 135.0
    max_velocity: !degrees 225.0
    max_effort: 30.0
  joint5:
    min_position: !degrees -178.0
    max_position: !degrees 178.0
    max_velocity: !degrees 225.0
    max_effort: 10.0
  joint6:
    min_position: !degrees -128.0
    max_position: !degrees 128.0
    max_velocity: !degrees 225.0
    max_effort: 10.0
  joint7:
    min_position: !degrees -360.0
    max_position: !degrees 360.0
    max_velocity: !degrees 225.0
    max_effort: 10.0
