controller_manager:
  ros__parameters:
    update_rate: 200 # Hz

    # Broadcasters
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Arm controllers
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 200 # Hz
    # joints:
    #   - right_hand_index
    # interfaces:
    #   - position
    #   - effort

left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_joint1
      - left_arm_joint2
      - left_arm_joint3
      - left_arm_joint4
      - left_arm_joint5
      - left_arm_joint6
      - left_arm_joint7

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      # left_joint1:
      #   trajectory: 0.005
      # left_joint2:
      #   trajectory: 0.005
      # left_joint3:
      #   trajectory: 0.005
      # left_joint4:
      #   trajectory: 0.005
      # left_joint5:
      #   trajectory: 0.005
      # left_joint6:
      #   trajectory: 0.005

right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_joint1
      - right_arm_joint2
      - right_arm_joint3
      - right_arm_joint4
      - right_arm_joint5
      - right_arm_joint6
      - right_arm_joint7

    command_interfaces:
      - position

    state_interfaces:
      - position

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true
    open_loop_control: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
      # right_joint1:
      #   trajectory: 0.005
      # right_joint2:
      #   trajectory: 0.005
      # right_joint3:
      #   trajectory: 0.005
      # right_joint4:
      #   trajectory: 0.005
      # right_joint5:
      #   trajectory: 0.005
      # right_joint6:
      #   trajectory: 0.005
